### ISSUE TITLE
Server start on MaxOS 10.14.6 throws error

### ISSUE THREAD

**Issue by pbhogale** [IATA-Cargo/Sandbox#2]
Having followed the instructions to get the one record server up and running, the server does not start and throws a fairly unhelpful error as seen below :

```
npm start

> onerecordserver@0.0.0 start /Users/User/Documents/Sandbox
> node ./bin/www

internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module '../utils'
Require stack:
- /Users/User/Documents/Sandbox/routes/companyRouter.js
- /Users/User/Documents/Sandbox/app.js
- /Users/User/Documents/Sandbox/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/User/Documents/Sandbox/routes/companyRouter.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/User/Documents/Sandbox/app.js:19:21)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/User/Documents/Sandbox/routes/companyRouter.js',
    '/Users/User/Documents/Sandbox/app.js',
    '/Users/User/Documents/Sandbox/bin/www'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onerecordserver@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the onerecordserver@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/User/.npm/_logs/2019-08-20T19_48_38_787Z-debug.log
```

the log file mentioned shows :

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.8.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.11.0
3 info using node@v12.8.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle onerecordserver@0.0.0~prestart: onerecordserver@0.0.0
6 info lifecycle onerecordserver@0.0.0~start: onerecordserver@0.0.0
7 verbose lifecycle onerecordserver@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle onerecordserver@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/User/Documents/Sandbox/node_modules/.bin$
9 verbose lifecycle onerecordserver@0.0.0~start: CWD: /Users/User/Documents/Sandbox
10 silly lifecycle onerecordserver@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle onerecordserver@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle onerecordserver@0.0.0~start: Failed to exec start script
13 verbose stack Error: onerecordserver@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid onerecordserver@0.0.0
15 verbose cwd /Users/User/Documents/Sandbox
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.8.1/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.8.1
19 verbose npm  v6.11.0
20 error code ELIFECYCLE
21 error errno 1
22 error onerecordserver@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the onerecordserver@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

any help would be much appreciated.

**Comment by andrablaj** [comment]
Thank you for the feedback. Indeed, I have forgotten to commit `utils.js`. This was fixed in https://github.com/IATA-Cargo/Sandbox/pull/3
